<template>
  <n-upload :custom-request="onUpload">
    <n-upload-dragger>
      <div style="margin-bottom: 12px">
        <n-icon :depth="3" size="48">
          <archive-outline />
        </n-icon>
      </div>
      <n-text style="font-size: 16px"> Click or drag a file to this area to upload</n-text>
      <n-p depth="3" style="margin: 8px 0 0 0">
        You can drop simulation output files here that were either
        generated through the Web-Interface, CLI or directly within python.
      </n-p>
    </n-upload-dragger>
  </n-upload>
</template>

<script setup>
import { useRouter } from "vue-router";
import { useLoadingBar, useMessage } from "naive-ui";
import { ArchiveOutline } from "@vicons/ionicons5";

import Simulation from "../../../SimulationObjects/Simulation";

import { setSimulationConfig, setSimulationSingleton } from "@/scripts/simulationSingleton";
import { persistSimulation } from "@/API/api";

const message = useMessage();
const loadingBar = useLoadingBar();
const router = useRouter();

/**
 * Uploads an existing simulation in JSON format
 * Important: No checks are performed to ensure that the uploaded JSON-File is indeed a simulation file
 * generated by the AirspaceAuctionSimulatior Suite! This could be extended in the future.
 * @param {UploadCustomRequestOptions} upload
 * @returns {Promise<void>}
 */
const onUpload = async (upload) => {
  loadingBar.start();
  const fileReader = new FileReader();
  fileReader.onload = async (event) => {
    const data = JSON.parse(event.target.result);
    await persistSimulation(data);
    const simulation = new Simulation(data.simulation, data.config, data.statistics, data.owner_map);
    await simulation.load();
    setSimulationSingleton(simulation);
    setSimulationConfig(data.config);
    await router.push({ name: "dashboard" });
  };
  fileReader.onerror = () => {
    loadingBar.error();
    message.error("Import failed!");
    throw new Error("Import failed!");
  };
  fileReader.readAsText(upload.file.file);
};
</script>

<style scoped></style>
